#!/bin/bash
# By: Anonymous Zpt
# Ofuscador De Anonymous Zpt
# Github: https://github.com/Anonymous-Zpt
# Youtube: http://www.youtube.com/c/AnonymousZpt
Anonymous_Zpt=$(mktemp)
base64 -d  >${Anonymous_Zpt}<<DIXIE
IyEgL2RhdGEvZGF0YS9jb20udGVybXV4L2ZpbGVzL3Vzci9iaW4vYmFzaAoKIyBDb2xvcnMKCkJM
az0nXDAzM1swOzMwbScKR0M9J1wwMzNbMDszN20nCkdPPSdcMDMzWzE7MzBtJwpDPSdcMDMzWzE7
MzZtJwpHPSdcMDMzWzE7MzJtJwpSPSdcMDMzWzE7MzFtJwpZPSdcMDMzWzE7MzNtJwpCPSdcMDMz
WzE7MzRtJwpQPSdcMDMzWzE7MzVtJwpXPSdcMDMzWzE7MzdtJwpSRT0nXDAzM1swbScKCmNsZWFy
CmVjaG8gLWUgIlsg4piGIF0gTlVOQ0EgREVKRVMgREUgQVBSRU5ERVIgOikiIHwgbG9sY2F0IC1h
IC1kIDMwIC1zIDMwCmVjaG8KZm9yICgoIGo9MTsgajw9OTsgaisrICkpOyBkbwoJZWNobyAtZSAi
JHtHT31UZXJtdXggQnkkUjokQyBDajckR08geEQgJGogIFxjIgpmb3IgKCggaT0wOyBpPD0xNTsg
aSsrICkpOyBkbwoJZWNobyAtZSAiJFIuXGMiCglzbGVlcCAwMC4wNQpkb25lCmVjaG8gLWUgIlxj
IgplY2hvIC1lICJcdCRSWyR7R0N9NjY2JFJdIgplY2hvCmRvbmUKZWNobyAtZSAiWyDimIYgXSBT
T0xPIERFUEVOREUgREUgVEkgOikiIHwgbG9sY2F0IC1hIC1kIDMwIC1zIDMwCnJlYWQgZW50ZXIK
Cg==
DIXIE
source ${Anonymous_Zpt}
rm -rf ${Anonymous_Zpt}
